Feat/distinct field
appbaseio/flutter-searchbox pull request #11
Opened 2021-05-20 14:20 UTC by anik-ghosh-au7

Support and examples added for `distinctField `& `distinctFieldConfig` props in flutter-searchbox - which returns distinct results based on a specified field.

Notion Link - https://www.notion.so/appbase/distinctField-prop-f14649fd05c544a993cbee11e1846c8c

Docs PR link - https://github.com/appbaseio/Docs/pull/186

Demo - 
https://www.loom.com/share/558c4f8619ba43ccaa35b4f3c50450d4

2021-05-24 22:05 UTC, bietkul requested changes
@anik-ghosh-au7 Fix the request changes.
How can you reach the end of the results? It seems like an issue with the `No more results` message.
![alt img](https://i.imgur.com/ErnuEx1.png)

2021-05-24 22:05 UTC, bietkul commented on searchbase/lib/src/searchcontroller.dart
> +  /// A string defining a field's name, used to return the distinct value documents.
@anik-ghosh-au7 Define docs with example.

2021-05-24 22:05 UTC, bietkul commented on searchbase/lib/src/searchcontroller.dart
> +  /// This property allows specifying additional options to the distinctField property.
@anik-ghosh-au7 Define docs with example.

2021-05-24 22:05 UTC, bietkul commented on flutter_searchbox/lib/flutter_searchbox.dart
> +  /// A string defining a field's name, used to return the distinct value documents.
@anik-ghosh-au7 Why are you not using the content from docs.appbase.io?
Please use the exact content with links and examples.
![alt img](https://i.imgur.com/xM7OFhu.png)

2021-05-24 22:05 UTC, bietkul commented on flutter_searchbox/lib/flutter_searchbox.dart
> +  /// This property allows specifying additional options to the distinctField property.
@anik-ghosh-au7 Fix content

2021-05-24 22:05 UTC, bietkul commented on flutter_searchbox/lib/flutter_searchbox.dart
> +  /// A string defining a field's name, used to return the distinct value documents.
Fix content

2021-05-24 22:05 UTC, bietkul commented on flutter_searchbox/lib/flutter_searchbox.dart
> +  /// This property allows specifying additional options to the distinctField property.
Fix content

2021-05-24 22:05 UTC, bietkul commented on flutter_searchbox/example_with_distinctField/lib/main.dart
> +                      distinctField: 'authors.keyword',
@anik-ghosh-au7 Remove it from here

2021-05-24 22:05 UTC, bietkul commented on flutter_searchbox/example_with_distinctField/lib/main.dart
> +                      distinctFieldConfig: {
@anik-ghosh-au7 Remove it from here

2021-05-24 22:05 UTC, bietkul commented on flutter_searchbox/example_with_distinctField/lib/results.dart
> +    searchController.results?.rawData?['hits']['hits'].forEach((hit) => {
@anik-ghosh-au7 What are you doing here? Can you write some comments?

2021-05-25 06:19 UTC, siddharthlatest commented
@anik-ghosh-au7 I would also add that `.idea/` dir files should be ignored (see .gitignore) and not be part of the PR.

2021-07-02 17:51 UTC, bietkul approved these changes

2021-07-02 17:51 UTC, bietkul commented on flutter_searchbox/lib/flutter_searchbox.dart
> +  /// String [optional] This prop returns only the distinct value documents for the specified field.
```suggestion
  /// This prop returns only the distinct value documents for the specified field.
```

2021-07-02 17:51 UTC, bietkul commented on flutter_searchbox/lib/flutter_searchbox.dart
> +  /// Object [optional] This prop allows specifying additional options to the distinctField prop.
```suggestion
  /// This prop allows specifying additional options to the distinctField prop.
```

2021-07-02 17:51 UTC, bietkul commented on flutter_searchbox/lib/flutter_searchbox.dart
> +  /// String [optional] This prop returns only the distinct value documents for the specified field.
```suggestion
  /// This prop returns only the distinct value documents for the specified field.
```

2021-07-02 17:51 UTC, bietkul commented on flutter_searchbox/lib/flutter_searchbox.dart
> +  /// Object [optional] This prop allows specifying additional options to the distinctField prop.
```suggestion
  /// This prop allows specifying additional options to the distinctField prop.
```

2021-07-02 17:51 UTC, bietkul commented on searchbase/lib/src/searchcontroller.dart
> +  /// String [optional] This prop returns only the distinct value documents for the specified field.
```suggestion
  /// This prop returns only the distinct value documents for the specified field.
```

2021-07-02 17:51 UTC, bietkul commented on searchbase/lib/src/searchcontroller.dart
> +  /// Object [optional] This prop allows specifying additional options to the distinctField prop.
```suggestion
  /// This prop allows specifying additional options to the distinctField prop.
```

2021-07-02 17:52 UTC, merged