fix: selectedfilters component allows only List/ Map values
appbaseio/flutter-searchbox pull request #18
Opened 2022-02-10 11:05 UTC by mohdashraf010897

**PR Type** 🐞 `Fix`

**Description** 
- [ ]  `SelectedFilters` component
    - [ ]  It doesn’t display the `string` type of values. Use it with `SearchBox` component and select a query. `SelectedFilters` only shows the `List` and `Map` values.
    
    ⇒ The ideal behavior is to provide filter values irrespective of the value type.

[📔 Notion](https://www.notion.so/appbase/Funda-Issues-bc9b05c3275b41eab77b7294ddb45781)

2022-02-11 14:00 UTC, bietkul requested changes

2022-02-11 14:00 UTC, bietkul commented on flutter_searchbox_ui/lib/src/utils.dart
> +  return val == null || false == val || "" == val;
```suggestion
  return val == null || val == "";
```

2022-02-14 06:06 UTC, mohdashraf010897 commented
@bietkul https://www.loom.com/share/f4cb55b4efd14971be07fb5b7bfdc792

2022-02-16 15:38 UTC, bietkul approved these changes

2022-02-16 16:39 UTC, merged