Added example for cloud STT service
appbaseio/flutter-searchbox pull request #4
Opened 2021-03-17 05:50 UTC by anik-ghosh-au7

- Added an example to demonstrate the integration of Google Speech-to-Text API with flutter searchbox

- demo -

https://www.loom.com/share/17a49ab1f4fc4299bb705945d2df8903

- walkthrough - 

https://www.loom.com/share/756b0ed69a454561b20d51cd2559976c

2021-04-12 14:13 UTC, bietkul requested changes
@anik-ghosh-au7 Please follow the following points:
- Code must be minimal, readable, and easy to understand.
- At the top of the class describe the component usage and explain functionality in brief
- Describe complex functionalities in comments
- Use variables, methods, and class names in a way that they are self-exploratory

2021-04-12 14:13 UTC, bietkul commented on flutter_searchbox/example_cloudSTT/README.md
> +5. Open audio_converter.dart file and paste the JSON object in here -
@anik-ghosh-au7 Can you add a quick video (without audio) to cover this process?

2021-04-12 14:13 UTC, bietkul commented on flutter_searchbox/example_cloudSTT/lib/main.dart
> +  setOverlay(bool status, String value, BuildContext context) async {
@anik-ghosh-au7 I'm not able to understand what is going here? Please add comments and use names for variables and methods which are self-exploratory.

2021-04-19 11:59 UTC, anik-ghosh-au7 commented on flutter_searchbox/example_cloudSTT/README.md
> +5. Open audio_converter.dart file and paste the JSON object in here -
@bietkul - https://recordit.co/WOHanl0NRX

2021-07-12 14:33 UTC, anik-ghosh-au7 commented
@siddharthlatest 

In order to merge the PR - 
      we have to use the latest flutter sdk and upgrade the versions for the following packages - 
      - path_provider - 2.0.2 (null safety)
      - google_speech - 2.0.1 (null safety)
      
      use an alternative package to get the audio input from the user
      - flutter_audio_recorder (null safety not available)

2021-07-12 15:50 UTC, siddharthlatest commented
@anik-ghosh-au7 Here's the library with null safety included in it: https://github.com/devaliakbar/flutter_audio_recorder. We should now be able to create / merge this PR. We can also resolve the conflicts over here.

2021-07-25 14:15 UTC, anik-ghosh-au7 commented
demo latest - https://loom.com/share/34df5c19521f42c699745e1a08783a78

2021-07-28 12:11 UTC, bietkul commented on flutter_searchbox/example_cloudSTT/lib/main.dart
> +                          // passing the Recorder as a custom action to the SearchBox widget
```suggestion
                          // using the custom action(mic icon) to handle voice search
```

2024-03-09 05:04 UTC, closed without merging